// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Delegates.cs">
//   Copyright (c) 2016. All rights reserved.
//   Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in Spritely.Redo source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Spritely.Redo
{
    using System;

    /// <summary>
    ///     Interface for reporting exceptions that occur during retry handling.
    /// </summary>
    /// <param name="exception">The exception.</param>
    public delegate void ExceptionListener(Exception exception);
}
