// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IRetryStrategy.cs">
//   Copyright (c) 2016. All rights reserved.
//   Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in Spritely.Redo source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Spritely.Redo
{
    /// <summary>
    ///     A strategy for retrying operations.
    /// </summary>
#if !SpritelyRecipesProject
    [System.CodeDom.Compiler.GeneratedCode("Spritely.Recipes", "See package version number")]
#pragma warning disable 0436
#endif
    public partial interface IRetryStrategy
    {
        /// <summary>
        ///     A retryable operation calls this method to determine if it should quit.
        /// </summary>
        /// <param name="attempt">The attempt.</param>
        /// <returns>true if operation should be cancelled, false otherwise.</returns>
        bool ShouldQuit(long attempt);

        /// <summary>
        ///     A retryable operation calls this method to introduce wait time before retrying again.
        /// </summary>
        /// <param name="attempt">The attempt.</param>
        void Wait(long attempt);
    }
#if !SpritelyRecipesProject
#pragma warning restore 0436
#endif
}
