// --------------------------------------------------------------------------------------------------------------------
// <copyright file="LinearDelayRetryStrategy.cs">
//   Copyright (c) 2016. All rights reserved.
//   Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in Spritely.Redo source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Spritely.Redo
{
    using System;
    using System.Threading;

    /// <summary>
    ///     A retry strategy that backs off with a linear decay (addition).
    /// </summary>
    public class LinearDelayRetryStrategy : IRetryStrategy
    {
        internal Func<long, TimeSpan, double, TimeSpan> calculateSleepTime = CalculateSleepTime;

        /// <summary>
        ///     Gets or sets the delay.
        /// </summary>
        /// <value>
        ///     The delay.
        /// </value>
        public TimeSpan Delay { get; set; }

        /// <summary>
        ///     Gets or sets the maximum retries.
        /// </summary>
        /// <value>
        ///     The maximum retries.
        /// </value>
        public int MaxRetries { get; set; }

        /// <summary>
        ///     Gets or sets the scale factor.
        /// </summary>
        /// <value>
        ///     The scale factor.
        /// </value>
        public double ScaleFactor { get; set; }

        /// <summary>
        ///     Initializes a new instance of the <see cref="LinearDelayRetryStrategy" /> class.
        /// </summary>
        /// <param name="scaleFactor">The scale factor.</param>
        /// <param name="maxRetries">The maximum retries.</param>
        /// <param name="delay">The delay.</param>
        public LinearDelayRetryStrategy(double scaleFactor, int maxRetries, TimeSpan delay)
        {
            ScaleFactor = scaleFactor;
            MaxRetries = maxRetries;
            Delay = delay;
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="LinearDelayRetryStrategy" /> class.
        /// </summary>
        /// <param name="scaleFactor">The scale factor.</param>
        public LinearDelayRetryStrategy(double scaleFactor)
        {
            ScaleFactor = scaleFactor;
            MaxRetries = TryDefault.MaxRetries;
            Delay = TryDefault.Delay;
        }

        /// <inheritdoc />
        public bool ShouldQuit(long attempt)
        {
            return attempt > MaxRetries;
        }

        /// <inheritdoc />
        public void Wait(long attempt)
        {
            var sleepTime = calculateSleepTime(attempt, Delay, ScaleFactor);

            Thread.Sleep(sleepTime);
        }

        internal static TimeSpan CalculateSleepTime(long attempt, TimeSpan delay, double scaleFactor)
        {
            var factor = ((attempt - 1) * scaleFactor);
            var safefactor = (factor < 0) ? 0 : factor;
            var totalDelay = delay.TotalMilliseconds + safefactor;

            var sleepTime = SafeDelay.ConstrainBounds(totalDelay);

            return sleepTime;
        }
    }
}
