// --------------------------------------------------------------------------------------------------------------------
// <copyright file="TryConfiguration.cs">
//   Copyright (c) 2016. All rights reserved.
//   Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in Spritely.Redo source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

using System;

namespace Spritely.Redo
{
    internal class TryConfiguration
    {
        public IRetryStrategy RetryStrategy { get; set; }
        public ExceptionListener ExceptionListeners { get; set; }
        public ExceptionCollection Handles { get; set; }

        public void Report(Exception ex)
        {
            this.ExceptionListeners(ex);
        }
    }
}
