// --------------------------------------------------------------------------------------------------------------------
// <copyright file="TryFunction.cs">
//   Copyright (c) 2016. All rights reserved.
//   Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in Spritely.Redo source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Spritely.Redo
{
    using System;
    using Spritely.Redo.Internal;

    /// <summary>
    ///     Part of fluent API when user calls Try.Running() with a function.
    /// </summary>
    /// <typeparam name="T">Type of the result of the call to f passed to Try.Running().</typeparam>
#if !SpritelyRecipesProject
    [System.Diagnostics.DebuggerStepThrough]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("Spritely.Recipes", "See package version number")]
#pragma warning disable 0436
#endif
    public partial class TryFunction<T> : TryOperation<TryFunction<T>>
    {
        private readonly Func<T> f;
        internal Func<Func<T>, Func<T, bool>, TryConfiguration, T> _until = Run.Until;

        /// <summary>
        ///     Initializes a new instance of the <see cref="TryFunction{T}" /> class.
        /// </summary>
        /// <param name="function">The function to call with retries.</param>
        /// <exception cref="System.ArgumentNullException">f;Running requires a valid function to call.</exception>
        public TryFunction(Func<T> function)
        {
            if (function == null)
            {
                throw new ArgumentNullException("function", "Running requires a valid function to call.");
            }

            f = function;
        }

        /// <summary>
        ///     Initiates the call and retries until the specified condition is satisfied or the retry strategy cancels the
        ///     request.
        /// </summary>
        /// <param name="satisfied">The operation that determines success.</param>
        public T Until(Func<T, bool> satisfied)
        {
            return _until(f, satisfied, _configuration);
        }

        /// <summary>
        ///     Initiates the call and retries until the result is not null or the retry strategy cancels the request.
        /// </summary>
        public T UntilNotNull()
        {
            return Until(v => v != null);
        }
    }
#if !SpritelyRecipesProject
#pragma warning restore 0436
#endif
}
